### PR TITLE
Add signal that is emitted when a node is removed

### PR DESCRIPTION
**Pull request by schlagenhauf**

### CODE REVIEW

**Comment by grindhold** [comment]
well, well, well.  so the hard API questions rise again.
The GFlow.Node is not supposed to have any methods/parameters/signals that relate to something the UI (GtkFlow) does. When the GFlow node disappears from the nodeview it is not really being deleted as it still continues to exist in memory as long as referenced somewhere else.

Would a signal on NodeView also fit your needs? Like this:

`public signal void NodeView.node_deleted(GFlow.Node node);`

**Comment by schlagenhauf** [comment]
I had a feeling that this would violate some architecture concepts.

Currently im referencing the libgtkflow nodes from my logic nodes directly, thus a per-node signal is easier to integrate. However a NodeView signal would also fit my needs in a sense that my architecture needs an overhaul anyway.

**Comment by grindhold** [comment]
added the functionality in `5fe14db`

thanks for your attempt on implementing it 👍

**Comment by schlagenhauf** [comment]
Once again, thanks for the fast and helpful response!

**Pull request closed without merging**
