### PR TITLE
Convert to Autotools

### PR DESCRIPTION
**Pull request by esodan**
I've added support for Autotools with following features:

* i18n
* Windows build
* Targeting 0.2 as stable API, building gtkflow-0.2.pc, libgtkflow-0.2.so and headers located at libgtkflow-0.2/libgtkflow, for parallel installation for future versions with API breaks
* Added GObject Introspection fixes for namespace information at vala source (at namespace-info.vala)

Not included yet:

* Valadoc support
* Unit Testing
* Examples

### CODE REVIEW

**Comment by esodan** [comment]
This pull request, add a fixes for python script example, plus the lasts.

**Comment by esodan** [comment]
Could you give me all messages logs, in order to see what is the problem please?

**Comment by esodan** [comment]
I've fixed the problem. Was a missing file.

**Comment by grindhold** [comment]
now it works nicely (though i don't understand it completely)

**Pull request merged**
